### ISSUE TITLE
RestClient - MD5 not getting calculated

### ISSUE THREAD

**Issue by t-anjan** [mgomes/api_auth#125]
https://github.com/mgomes/api_auth/blob/5a1bafe7581b29188cc3487325bcbbdd0237764d/lib/api_auth/request_drivers/rest_client.rb#L32

```
def populate_content_md5
   return unless [:post, :put].include?(@request.method)
   @request.headers['Content-MD5'] = calculated_md5
   save_headers
end
```

In the above line `@request.method` returns a string. But the code is checking for a symbol. Because of this, when signing the request, the MD5 does not get added to the header at all.

Is this a bug or am I missing something here?

I am using api-auth version 2.0.1 and rest-client version 2.0.0 .

**Comment by kjg** [comment]
After a quick look at the rest-client gem it looks like starting with [2.0 rest-client now normalizes #method to a string](https://github.com/rest-client/rest-client/commit/e85a954ed821804fad245891dd75e54fe2888985)

We should update api_auth to account for this. Nice find!
