### ISSUE TITLE
How to use with Grape ?

### ISSUE THREAD

**Issue by c0ze** [mgomes/api_auth#131]
Is it possible to use this gem with grape ?
I've added the gem, I have access to the ApiAuth module, but when I try to call `sign!` or `authenticated?` they seem not to be available. Is some kind of initialization necessary ?

**Comment by c0ze** [comment]
nevermind. I was checking out `api_auth` which was installing an archaic version.
`api-auth` is where its at.

**Comment by taylorthurlow** [comment]
I made the same mistake, thanks.
