### ISSUE TITLE
Drop support of Ruby 1.X and Rails 2.X, Rails 3.X

### ISSUE THREAD

**Issue by fwininger** [mgomes/api_auth#140]
Hello, 

I would like to know if it's possible to drop the support of ruby 1.X  and rails [2,3].X ?
I would be happy to do a deep refactoring of the gem using the ruby 2.X syntax.

Does it make sense for you?

**Comment by kjg** [comment]
I'm not opposed to it. I'm curious though, what is your motivation for this?

**Comment by fwininger** [comment]
I would like to clean the code like "respond_to?('class_attribute')", use last rubocop linter and add feature like #120.

**Comment by fwininger** [comment]
This can be close ?

**Comment by kjg** [comment]
closed by #141
