### ISSUE TITLE
WARNING: `Faraday::Request#method` is deprecated; use `#http_method` instead.

### ISSUE THREAD

**Issue by andrewhavens** [mgomes/api_auth#190]
I'm seeing this warning while using Faraday 1.3.0 and api-auth 2.4.1:

```
WARNING: `Faraday::Request#method` is deprecated; use `#http_method` instead. It will be removed in or after version 2.0.
`Faraday::Request#method` called from /Users/andrew/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/api-auth-2.4.1/lib/api_auth/request_drivers/faraday.rb:24:in `populate_content_md5'
WARNING: `Faraday::Request#method` is deprecated; use `#http_method` instead. It will be removed in or after version 2.0.
`Faraday::Request#method` called from /Users/andrew/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/api-auth-2.4.1/lib/api_auth/request_drivers/faraday.rb:43:in `http_method'
```

**Comment by fwininger** [comment]
It's seems to need Faraday >= 1.1.0

**Comment by andrewhavens** [comment]
Thanks! Do you mind deploying a new release version?

**Comment by GregMacdonald** [comment]
@fwininger Thanks for this fix. My builds are heavily polluted with this warning. Would appreciate a rev of the gem if you've time to tackle it.

**Comment by fwininger** [comment]
Hi @andrewhavens / @GregMacdonald I don't have the access to rubygems to do a release.

@mgomes / @kjg can you release a new version from the master branch ? I had the support of ruby 3.0 and rails 6.1 and drop old ruby versions. Thanks !

**Comment by mgomes** [comment]
@fwininger should we call this 3.0? Seems like the dropping of MRI versions warrants a major version bump.

**Comment by fwininger** [comment]
@mgomes for me 2.5.0 is good. I thinks 2.4.0 drop MRI 2.3 and rails 4.

**Comment by mgomes** [comment]
Version 2.5.0 has been released!

**Comment by fwininger** [comment]
@mgomes thanks
