### ISSUE TITLE
GET requests through ActiveResource fail authentication due to Content-Type mismatch

### ISSUE THREAD

**Issue by joshlarsen** [mgomes/api_auth#54]
##### Environment
```
Rails 4.1.5 (client & server)
ActiveResource 4.0.0 (client)
api-auth 1.2.6 (client & server)
```
##### Issue
Server side interprets `Content-Type` as `text/plain` when the `Content-Type` header is missing (as it should be on a **GET** request). Since the auth signature was calculated with a blank `Content-Type` on the client and `Content-Type` of `text/plain` on the server, the signatures will not match.
##### Workaround
Force a `Content-Type` header from the client side with something like:
```ruby
class ApiModel < ActiveResource::Base
	self.site = "http://api-server/api/v1"
	headers["Content-Type"] = "application/json"
	with_api_auth(access_id, secret_key)
end
```
In this case, client and server will both use `application/json` as the content type in computing the signature.

Though this is probably not ideal since `Content-Type` is not a valid **GET** header. A better solution might be to check for the presence of the `Accept` header and skip the `Content-Type` header in calculating the signature for **GET** requests.

**Comment by tombroomfield** [comment]
Thank you @joshlarsen - Scratching my head for hours on this.
