### ISSUE TITLE
Writing rails controller tests for api-auth

### ISSUE THREAD

**Issue by MichaelSp** [mgomes/api_auth#57]
I'm trying to write test for an authenticated API-Access like so

``` ruby
test 'api access with valid request' do
      @user = users(:one)
      @request = ApiAuth.sign!(@request, @user.id, @user.secret_access_token)
      get :index
      assert_response :success
end
```

The server side validation looks like this

``` ruby
module Api
  class ApplicationController < ActionController::Base
    respond_to :json
    before_action :api_authenticate

     def api_authenticate
      user_id = ApiAuth.access_id(request)
      raise 'id not found' if user_id.blank?
      @current_user = User.find(user_id)
      raise 'user not found' if @current_user.blank?
      raise 'token not valid' unless ApiAuth.authentic?(request, @current_user.secret_access_token)
     rescue Exception => e
       logger.warn "API-Call failed: #{e.message}"
       head :unauthorized
    end
  end
end
```

This simple test case does not work. It always fails with `Minitest::Assertion: Expected response to be a <success>, but was <401>`.
I was able to track this down to the following issue:
The @request gets signed **without** the `PATH-INFO` header. And it gets authenticated **with** the `PATH-INFO`. The `PATH-INFO` is set inside of `get :index`. So there is no way to sign the request after `PATH-INFO` has been set.

What do you think? Is there a way to get the test running?

**Comment by evanjmg** [comment]
how can I test whether it is on? I put mine in a before_action in my api_controller.

**Comment by MichaelSp** [comment]
I don't understand "whether it is on". What is "it"?

**Comment by evanjmg** [comment]
how can I test if the before_action running? Sometimes I comment it out for postman/curl requests; it'd be nice to test whether api_auth is actually being used in my api.

**Comment by MichaelSp** [comment]
You can test if there's a `Authorization` header set in your request.
