### ISSUE TITLE
ApiAuth.authentic? always return false

### ISSUE THREAD

**Issue by moustafasallam** [mgomes/api_auth#68]
I have set up the client side as the following:

```
  	access_id = "1"
    secret_key = 'hello'

    headers = { 'Content-MD5' => Digest::MD5.hexdigest('go_to_space!'),
        'Content-Type' => "text/plain",
        'Date' => Time.zone.now }
    request = RestClient::Request.new(:url => "http://localhost:4000/",
        :headers => headers,
        :method => :get)

    @signed_request = ApiAuth.sign!(request, access_id, secret_key)
    @headers = ApiAuth::Headers.new(@signed_request)
    @response = @signed_request.execute
```
And the server side as the following:

```
    access_id = ApiAuth.access_id(request)
    api_client = ApiClient.where(:id => access_id.to_i).last
    if api_client then
      result = ApiAuth.authentic?(request, api_client.secret)
    end
```

But ApiAuth.authentic? result is always false. Any clue.

I am using api-auth 1.3.1
Thank you

**Comment by connerfritz** [comment]
I'm also encountering this problem.

**Comment by kjg** [comment]
@moustafasallam, It looks like a Content-MD5 is being set, but then the request is a GET request. A GET request doesn't typically have any content. My guess is that the server is not seeing any content and thus the Content-MD5 is not matching.

Another possible gotcha to watch out for is to make sure the client and servers are both set to the correct time.

**Comment by moustafasallam** [comment]
@kjg, Thank you. It is time stamp issue indeed. I removed adding the date to the client request http header and it works now just fine.

**Comment by mgomes** [comment]
@moustafasallam Glad to hear it. You should really consider syncing the time, though. It prevents replay attacks by ensuring packets can't get re-sent.
