### ISSUE TITLE
Post requests from Net:HTTP don't calculate correct MD5 because of missing RAW_POST_DATA in the env

### ISSUE THREAD

**Issue by DiegoSalazar** [mgomes/api_auth#70]
I'm using `Net::HTTP` to send requests to my Rails 4.1.8 app running API-Auth 1.2.5. My requests were failing authentication and I tracked it down to the `calculated_md5` method in the `ActionControllerRequest` driver. It's checking for `@request.env.has_key?('RAW_POST_DATA')` but according to `ActionDispatch::Request` in the `raw_post` method:

```ruby
# ActionDispatch::Request
def raw_post
  unless @env.include? 'RAW_POST_DATA'
    raw_post_body = body
    @env['RAW_POST_DATA'] = raw_post_body.read(content_length)
     raw_post_body.rewind if raw_post_body.respond_to?(:rewind)
   end
   @env['RAW_POST_DATA']
end
```

The `RAW_POST_DATA` env var does not get set until calling `raw_post`. So in your `calculated_md5` method, the check for `@request.env.has_key?('RAW_POST_DATA')` will fail even though `@request.raw_post` will correctly return the raw post data.

Currently, I'm getting around this by calling `request.raw_post` in my controller before doing the `ApiAuth.authentic?` call. And that makes it work.

**Comment by kjg** [comment]
I believe this issue has been fixed. Please re-open if not.
