### ISSUE TITLE
How would you make a curl request?

### ISSUE THREAD

**Issue by yelvert** [mgomes/api_auth#76]
I've been trying

```
curl --header "Content-Type: application/json" --header "Authorization: APIAuth $access_key:$(echo -n "application/json,,$uri,$(TZ=GMT date "+%a, %d %b %Y %T %Z")" | openssl dgst -sha1 -hmac "$secret_key" "$@" | base64)" --header "Date: $(TZ=GMT date "+%a, %d %b %Y %T %Z")" $full_url
```

but the `signatures_match?` fail every time. I've ensured that the keys are valid and that the canonical strings match, but the signatures don't.

**Comment by kjg** [comment]
api_auth is using `OpenSSL::HMAC.digest` (not to be confused with `OpenSSL::HMAC.hexdigest`).

By default `openssl dgst -sha1 -hmac` is going to calculate a hexdigest, try `openssl dgst -sha1 -binary -hmac`

```ruby
Base64.strict_encode64(OpenSSL::HMAC.digest(digest, "123", "abc"))
=> "VAsMU9SSWDe9krP3Gr56nXC2dsQ="
```

```bash
echo -n "abc" | openssl dgst -sha1 -binary -hmac "123" | base64
VAsMU9SSWDe9krP3Gr56nXC2dsQ=
```

**Comment by c0ze** [comment]
Just in case you've not figured out what is going wrong, you need to add the request method in your canonical string. This worked for me :

```
HOST=http://localhost:9292
URI=/v1/users
UUID=SOME_ACCESS_ID
SECRET_KEY=SOMEKEY
CONTENT_TYPE=application/json
DATE=$(TZ=GMT date "+%a, %d %b %Y %T %Z")
curl -H "Content-Type: $CONTENT_TYPE" -H "Authorization: APIAuth $UUID:$(echo -n "GET,$CONTENT_TYPE,,$URI,$DATE" | openssl dgst -sha1 -binary -hmac $SECRET_KEY "$@" | base64)" -H "Date: $DATE" "$HOST$URI"
```

If you are going to make a `POST` (or anything with a body) I guess you would need to calculate md5 of the body and embed it into canonical string as well.

https://github.com/mgomes/api_auth/blob/489f0e38ed7d1a1b08b4376ad04062f30f373c2c/lib/api_auth/headers.rb#L57
