### ISSUE TITLE
Generated keys always contain a new line character

### ISSUE THREAD

**Issue by kevkon3** [mgomes/api_auth#77]
We have noticed that all of the secret keys being generated are containing a new line character at the exact same spot. This has caused some issues with some other libraries that do not properly handle the new line character.

A quick google search led us to find that using b64encode in ruby will cause this to happen: http://stackoverflow.com/a/2621023/81193

Indeed, b64encode is being used used in base.rb::generate_secret_key. The fix may be as simple strict_encode64 instead. Normally I would create a PR, but I am not very familiar with ruby and I would have no idea where to begin to validate that my PR fixes the issue.

**Comment by kjg** [comment]
You may need to update your version of api_auth. This has been fixed via

https://github.com/mgomes/api_auth/pull/22
https://github.com/mgomes/api_auth/pull/34

resulting in: https://github.com/mgomes/api_auth/blob/1808da747c727f63a7a4514637489b90b6f0129f/lib/api_auth/helpers.rb#L5
