### ISSUE TITLE
Documentation uses incorrect before_filter

### ISSUE THREAD

**Issue by ShadowRadiance** [mgomes/api_auth#79]
The sample before_filter does not prevent access.

before_filter/before_action need to actively redirect/render to stop processing.

maybe something like:

```ruby
    before_filter :api_authenticate

    def api_authenticate
      @current_account = Account.find_by_access_id(ApiAuth.access_id(request))
      return head(:unauthorized) if @current_account.nil?
      return head(:unauthorized) unless ApiAuth.authentic?(request, @current_account.secret_key)
    end
```

**Comment by kjg** [comment]
Thanks for bringing this to our attention! It looks like there is a PR to update the README to address this issue. Please let us know if this PR looks good to you or if it could use further modification: https://github.com/mgomes/api_auth/pull/78/files

**Comment by ShadowRadiance** [comment]
Yes that looks good (technically :unauthorized = 401 and might be easier to read)

**Comment by matthewblack** [comment]
:+1:
