### ISSUE TITLE
Update ReadMe to reflect that only PUT and POST sign requests

### ISSUE THREAD

**Issue by jgujgu** [mgomes/api_auth#92]
The example you list in the ReadMe breaks on get requests: 

```ruby
    def api_authenticate
      @current_account = Account.find_by_access_id(ApiAuth.access_id(request))
      head(:unauthorized) unless @current_account && ApiAuth.authentic?(request, @current_account.secret_key)
    end
```
I had to get around this by putting in a put/post guard clause:
```ruby
    def api_authenticate
        if request.put? || request.post?
          @current_account = Account.find_by_access_id(ApiAuth.access_id(request))
          head(:unauthorized) unless @current_account && ApiAuth.authentic?(request, @current_account.secret_key)
        end
    end
```
This line in the code clearly shows that only put/post requests are signed (However, the ApiAuth gem only allows for PUT and POST requests to be signed (https://github.com/mgomes/api_auth/blob/c80c998ccedf303ae3e14c4481cfe40e959ee94e/lib/api_auth/request_drivers/rest_client.rb#L35).

**Comment by kjg** [comment]
GET requests should work just fine as is. Make sure the Content-Type header is being properly set in your testing. Some server side libraries will add a content type header even if the client side didn't specify one, and this can cause the mismatch.

The code you link it is for "content_md5" which is just one of the headers included in the canonical string. This header contains the md5 hash of the body of the http request. Only POST and PUT and PATCH http methods can contain a content body.

Please let us know if you need any more help making the GET request to work as expected. Good Luck!

**Comment by jgujgu** [comment]
@kjg I appreciate your response. The author of active-rest-client informed me that he fixed this bug in his new maintained gem of the same kind, https://github.com/andyjeffries/flexirest.
