### ISSUE TITLE
Get requests not working with Flexiclient (ActiveRestClient)

### ISSUE THREAD

**Issue by jgujgu** [mgomes/api_auth#93]
I may not have outlined my problem clearly in my earlier issue raised. @kjg explained that GET requests do in fact work, but I don't think I fully understand how, or the proper implementation to make them work.

Using Flexiclient, my `GET` request reaches https://github.com/mgomes/api_auth/blob/master/lib/api_auth/base.rb#L42 and then eventually https://github.com/mgomes/api_auth/blob/master/lib/api_auth/base.rb#L100. The canonical string at this point looks like `application/x-www-form-urlencoded,,/users?id=18,Mon, 18 Jan 2016 17:15:50 GMT`, which makes sense, because in the form `'http method,content-type,content-MD5,request URI,timestamp'`, the content-MD5 should indeed be blank. Perhaps it is out of the scope of `api-auth`, but should `Flexiclient` be doing something differently in order for a `GET` request to properly pass the `authentic?` method?

**Comment by kjg** [comment]
Can you check what the canonical string on the server side is?

**Comment by jgujgu** [comment]
@kjg I apologize for not clearly stating where I am having trouble. The canonical string on the server side is indeed what I stated earlier, `application/x-www-form-urlencoded,,/users?id=18,Mon, 18 Jan 2016 17:15:50 GMT`.

At https://github.com/mgomes/api_auth/blob/master/lib/api_auth/base.rb#L42, for my `GET` request, once it executes
```ruby
def signatures_match?(headers, secret_key, options)
    match_data = parse_auth_header(headers.authorization_header)
    return false unless match_data

    options = options.merge(:with_http_method => true)

    header_sig = match_data[2]
    calculated_sig_no_http = hmac_signature(headers, secret_key, {})
    calculated_sig_with_http = hmac_signature(headers, secret_key, options)
    header_sig == calculated_sig_with_http || header_sig == calculated_sig_no_http
end
```
the `header_sig = 8GEVRkzLlzOnIQTERD7OVzzOtfU=`, `calculated_sig_with_http = QCeTcgEPfQpKp+ctmheDAtZTXcs=`, and `calculated_sig_no_http = Th+N23VayD3gry6rX4WRpt8O1X8=`.

For `PUT/POST` requests, the `calculated_sig_no_http` matches correctly to the `header_sig`, and I expected the same for  `GET` requests.

**Comment by kjg** [comment]
`application/x-www-form-urlencoded` as the content-type for a GET request doesn't really make sense. What server side request framework are you using?

On the client side what does the canonical string look like before sending the request to the server.

My guess is the client side isn't specifying a content-type, and the server side request framework is filling one in (when it shouldn't).

**Comment by jgujgu** [comment]
@kjg :D I appreciate your patience with me. I found that the `request URI` client-side did not have a `/`, whereas once it got to the server it did indeed have a `/`. Debugging and putting the slash in provided the desired behavior.
